force-app/main/default/objects/ApexErrorLog__c/ApexErrorLog__c.object-meta.xml
<CustomObject>
    <description>Contains all Error Logs generated during the process</description>
    <label>Apex Error Log</label>
    <nameField>
        <label>Error Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Apex Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ApexErrorLog__c/fields/ApexClass__c.field-meta.xml
<CustomField>
    <fullName>ApexClass__c</fullName>
    <description>Apex class name of generated error</description>
    <label>Apex Class</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ApexErrorLog__c/fields/ErrorLine__c.field-meta.xml
<CustomField>
    <fullName>ErrorLine__c</fullName>
    <description>Error line number</description>
    <label>Error Line</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ApexErrorLog__c/fields/ErrorMessage__c.field-meta.xml
<CustomField>
    <fullName>ErrorMessage__c</fullName>
    <description>Apex error message</description>
    <label>Error Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ApexErrorLog__c/fields/ExceptionType__c.field-meta.xml
<CustomField>
    <fullName>ExceptionType__c</fullName>
    <description>Type of Exception generated</description>
    <label>Exception Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ApexErrorLog__c/fields/LogType__c.field-meta.xml
<CustomField>
    <fullName>LogType__c</fullName>
    <description>Type of Log generated by Apex Class</description>
    <label>Log Type</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ApexErrorLog__c/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <description>Apex method that has generated the error</description>
    <label>Method</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ApexErrorLog__c/fields/Severity__c.field-meta.xml
<CustomField>
    <fullName>Severity__c</fullName>
    <description>Gravity Related of Exception generated</description>
    <label>Severity</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ApexErrorLog__c/fields/StackTrace__c.field-meta.xml
<CustomField>
    <fullName>StackTrace__c</fullName>
    <description>List of operations in error</description>
    <label>Stack Trace</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ApexErrorLog__c/fields/SupportTeam__c.field-meta.xml
<CustomField>
    <fullName>SupportTeam__c</fullName>
    <description>Support Team of Exception generated</description>
    <label>SupportTeam</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ApexErrorLog__c/fields/Timestamp__c.field-meta.xml
<CustomField>
    <fullName>Timestamp__c</fullName>
    <description>Timestamp of operation</description>
    <label>Timestamp</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ApexErrorLog__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User who performed the operation</description>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Error_Log</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Insert_Error_Log__e/Insert_Error_Log__e.object-meta.xml
<CustomObject>
    <label>Insert Error Log</label>
    <pluralLabel>Insert Error Logs</pluralLabel>
</CustomObject>

force-app/main/default/objects/Insert_Error_Log__e/fields/ApexClass__c.field-meta.xml
<CustomField>
    <fullName>ApexClass__c</fullName>
    <description>Apex class name of generated error</description>
    <label>Apex Class</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insert_Error_Log__e/fields/ErrorLine__c.field-meta.xml
<CustomField>
    <fullName>ErrorLine__c</fullName>
    <description>Error line number</description>
    <label>Error Line</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insert_Error_Log__e/fields/ErrorMessage__c.field-meta.xml
<CustomField>
    <fullName>ErrorMessage__c</fullName>
    <description>Apex error message</description>
    <label>Error Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Insert_Error_Log__e/fields/ExceptionType__c.field-meta.xml
<CustomField>
    <fullName>ExceptionType__c</fullName>
    <description>Type of Exception generated</description>
    <label>Exception Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insert_Error_Log__e/fields/LogType__c.field-meta.xml
<CustomField>
    <fullName>LogType__c</fullName>
    <description>Type of Log generated by Apex Class</description>
    <label>Log Type</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insert_Error_Log__e/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <description>Apex method that has generated the error</description>
    <label>Method</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insert_Error_Log__e/fields/Severity__c.field-meta.xml
<CustomField>
    <fullName>Severity__c</fullName>
    <description>Severity Related of Exception generated</description>
    <label>Severity</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insert_Error_Log__e/fields/StackTrace__c.field-meta.xml
<CustomField>
    <fullName>StackTrace__c</fullName>
    <description>List of operations in error</description>
    <label>Stack Trace</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Insert_Error_Log__e/fields/SupportTeam__c.field-meta.xml
<CustomField>
    <fullName>SupportTeam__c</fullName>
    <description>Support Team of Exception generated</description>
    <label>SupportTeam</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insert_Error_Log__e/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <description>User who performed the operation</description>
    <label>User</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PwcErrorLogEventTriggerHandler.cls
/**
 * @description       : 
 * @author            : Stefano Callisto
 * @group             : PwC
 * @last modified on  : 04-24-2024
 * @last modified by  : Stefano Callisto
**/
public with sharing class PwcErrorLogEventTriggerHandler extends TriggerHandler {
    protected override void afterInsert() {
        List<sObject> errorList = new List<sObject>();
        List<sObject> errorListHighGravity = new List<sObject>();
        for (Insert_Error_Log__e event : (List<Insert_Error_Log__e>) Trigger.New) {

            sObject log = PwcUtils.generateSObject('ApexErrorLog__c');
            log.put('User__c', event.User__c);
            log.put('ErrorMessage__c', event.ErrorMessage__c);
            log.put('ExceptionType__c', event.ExceptionType__c);
            log.put('ErrorLine__c', event.ErrorLine__c);
            log.put('StackTrace__c', event.StackTrace__c);
            log.put('ApexClass__c', event.ApexClass__c);
            log.put('Method__c', event.Method__c);
            log.put('LogType__c', event.LogType__c);
            log.put('Timestamp__c', event.Timestamp__c);
            log.put('Severity__c', event.Severity__c);
            log.put('SupportTeam__c', event.SupportTeam__c);
            errorList.add(log);
        }
        System.debug(LoggingLevel.DEBUG, 'DebugInErrorLog: ' + errorList);
        insert errorList;
        System.debug(LoggingLevel.DEBUG,JSON.serialize(errorListHighGravity));
        System.debug(LoggingLevel.DEBUG,JSON.serialize(errorList));

    }
}